version: "3.9"

services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - .:/app   # for development (auto reflect changes)
    restart: unless-stopped